### ISSUE TITLE
[Security] This method should not be called on the main thread as it may lead to UI unresponsiveness. 

### ISSUE THREAD

**Issue by chenxi92** [helpshift/HelpshiftX#2]
## Description

I invoked the `[Helpshift showConversationWith:config:];` method at the main thread after I installed the HelpshiftX SDK, and the Xcode console showed me two warnings:

> This method should not be called on the main thread as it may lead to UI unresponsiveness.

## Environment

HelpshiftX SDK Version: 10.2.3

Xcode: 14.2

Simulator: iPhone 14 Pro

Integration: Manually

## Addition

I run the code on my iPhone 6s iOS 14.0 without warning.

## Expecations
No warning on Simulator

**Comment by arif-helpshift** [comment]
Dear @chenxi92,

I hope this message finds you well. I appreciate you sharing the details about this issue.

Upon reviewing the information you shared, I was able to successfully reproduce it. It appears to be an issue or warning that occurs when utilizing `WKWebView` to load the Web View, such as when opening Chat or Help Center within the SDK.

For some developers, Xcode 14.3 resolved the issue. Link: https://developer.apple.com/forums/thread/712074?page=5. While this is promising, we will need to conduct further testing to verify this claim and determine if it can be considered as a viable solution.

To verify the issue independently, I created a new project integrating `WKWebView` and loaded a sample URL without integrating Helpshift SDK. During debugging, I encountered the same warning you described. This suggests that the issue lies with `WKWebView` itself, rather than with the Helpshift SDK. Link: https://www.hackingwithswift.com/forums/swiftui/xcode-14-warning-this-method-should-not-be-called-on-the-main-thread-as-it-may-lead-to-ui-unresponsiveness/17431/17432

If you have any additional insights, suggestions, or further developments regarding this issue, we would greatly appreciate your input and encourage you to reopen the issue for more information/discussion.
